### ISSUE TITLE
Publisher via LinkML

### ISSUE THREAD

**Issue by borsna** [Colectica/cogs#314]
Basic work done but needs more work.

- [ ] check output and handling of properies
- [ ] trigger LinkML after yaml is outputed
- [ ] handle IdentifiableType:
  ```yaml
  IdentifiableType:
    unique_keys:
      main:
        unique_key_slots:
          - URN
          - Agency
          - ID
          - Version
  ```

first draft: https://github.com/Colectica/cogs/commit/d996ddbd463c1f2906260a02952311e08343b79b
